services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: private-bot-ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http --url=${NGROK_DOMAIN} ${NGROK_FORWARD} 
    restart: unless-stopped
